services:
  magentic-rfi-ui-browser:
    build:
      context: .
      dockerfile: docker/magentic-ui-browser-docker/Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET:-changeme}
    volumes:
      - .:/workspace
    ports:
      - "8081:8081"
    command: magentic-ui --host 0.0.0.0 --port 8081
